#+AUTHOR: Maximo Tejeda P.
#+TITLE: Blog me a Blog service
#+EMAIL: Maximotejeda@gmail.com


* What is all this about?:
As an Org user i want to be able to write my text in Org-mode in emacs and manage a service to expose the text on an static Web page using Go templates and exported files as webpage from Org-mode,  my main goal is to mantain an eye in a folder which will be recurrently scanned in case of any file is modified or a new file is added or removed to update the content of the blog.

** Stack
As my main stack i'll be using:
- Go: for my Rest service and Templates generator.
- Emacs: as my editing tool and latext to export to a convenient format.
- Docker: to create an image with my binary
- SQLite: for and independant service to manage Comment in a future, and content.
- Ingress: to expose the service to the internet through a domain
- kubernets to orquestrate all my secrets and services.

** The Structure
The Project will  be structured as follow:
- cmd: will contain the main file where the service will be build
- Internal: Will contains the package that will be accessed through main to make different tasks
- web: Will contain the templates for the differents places in the Blog.
- db: will contain the post database 
