apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blog-db-nfs-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  storageClassName: nfs-w1-csi
  volumeMode: Filesystem
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 200Mi
  phase: Bound
