apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: blog-ingress
  namespace: default
spec:
  ingressClassName: public
  rules:
  - host: blog.maximotejeda.com
    http:
      paths:
      - backend:
          service:
            name: blog-svc
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - blog.maximotejeda.com
    secretName: blog-certs