apiVersion: v1
kind: Service
metadata:
  annotations:
  name: blog-svc
  namespace: default
spec:
  ipFamilies:
  - IPv4
  ports:
  - name: serve
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: blog
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
